import '@fontsource/roboto/300.css'
import '@fontsource/roboto/400.css'
import '@fontsource/roboto/500.css'
import '@fontsource/roboto/700.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { MaterialThemeProvider } from '@/providers'
import { MenuNavigation } from '@/components'
import { menuRoutes } from '@/definition'
import { NavigationProvider } from '@/providers/NavigationProvider'
import { SiteHeader } from '@/components/SiteHeader'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <MaterialThemeProvider>
        <body className={inter.className}>
          <SiteHeader />
          <div id="contenu" className="container mx-auto">
            <div className="grid grid-cols-12 gap-x-4">
              <div className="border-r-2 border-violet-950 col-span-2 h-screen">
                <NavigationProvider />
              </div>
              <div className="col-span-10 pt-6">{children}</div>
            </div>
          </div>
        </body>
      </MaterialThemeProvider>
    </html>
  )
}
